name: Test junit
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'junitResults.xml'
      - name: Build count
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: "count"
              name: "ci.tests.passed"
              value: ${{ steps.run_tests.outputs.passed }}
              host: ${{ github.repository_owner }}
              tags:
                - "repo:${{ github.repository }}"
                - "branch:${{ github.head_ref }}"
      #- name: Publish to wiki
      #  uses: dmnemec/copy_file_to_another_repo_action@main
      #    with: |
      #      source_file: ${{github.workspace}}/junit-report.md
      #      destination_repo: "${{ github.repository }}.wiki"
      #      destination_branch: 'master'
      #      user_email: 'nwithers@ecr.ai'
      #      user_name: 'nwithers-ecr'
      #      commit_message: "junit report"
