# Copyright 2022, Edge Case Research, Inc.
# Confidential

name: Validate PR
on: # rebuild any PRs and main branch changes
  pull_request_target:
    branches:
      - main

jobs:
  pr_merge:
    name: "PR Merge"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head.ref }}
          fetch-depth: 0

      - name: Pre-build Merge
        run: |
          echo git --version
          echo "$(git merge-base ${{ github.base_ref }} HEAD)"
          git read-tree -muv "$(git merge-base ${{ github.base_ref }} HEAD)" ${{ github.base_ref }} HEAD
          echo $?
