# Copyright 2022, Edge Case Research, Inc.
# Confidential

name: Validate PR
on: # rebuild any PRs and main branch changes
  pull_request_target:
    branches:
      - main

jobs:
  pr_merge:
    name: "PR Merge"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pre-build Merge
        run: |
          main=$(git rev-parse ${{ github.base_ref }})
          head=$(git rev-parse ${{ github.head_ref }})
          git read-tree -muv "$(git merge-base $main $head )" $main $head
