# Copyright 2022, Edge Case Research, Inc.
# Confidential

name: Test matrix
on:
  workflow_dispatch:

jobs:
  alpha:
    name: "matrix ${{ matrix.dir }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        letter: ["a", "b", "c"]
    outputs:
      letter: ${{ matrix.letter }}
    steps:
      - name: Echo matrix
        run: echo ${{ matrix.letter }}
                
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: release
          append: true
          number: 1
          message: |
            ${{ matrix.letter }}

  out:
    name: "cat together"
    runs-on: ubuntu-20.04
    needs: alpha
    steps:
      - name: Echo matrix
        run: echo ${{ needs.alpha.outputs.letter }}
